### ISSUE TITLE
Correlation Score = 0.53626

### ISSUE THREAD

**Issue by Shi-Yu7** [JasonYao81000/MLDS2018SPRING#1]
What is Correlation Score？accuracy or rouge？thanks

**Comment by JasonYao81000** [comment]
Correlation Score is decided by another model with the sigmoid output, you can treat it as a discriminator.
The higher correlation score means our chatbot produce the more correct sentences.
See more details in [here](https://docs.google.com/presentation/d/1GxaPl3_dGibYTlrg6WlvNTQHS2g4M30I37pVCZsS6tM/edit#slide=id.g381526074c_0_18).
