### ISSUE TITLE
No such file or directory: './AnimeDataset/testing_tags.txt'

### ISSUE THREAD

**Issue by siryne** [JasonYao81000/MLDS2018SPRING#6]
where can I get the Anime dataset?

**Comment by yao-jason** [comment]
You can download the Anime dataset from [here](https://drive.google.com/drive/folders/1mCsY5LEsgCnc0Txv0rpAUhKVPWVkbw5I?usp=sharing).
Furthermore, you can try extra dataset from [here](https://drive.google.com/file/d/1tpW7ZVNosXsIAWu8-f5EpwtF3ls3pb79/view).

Browse the [slide](https://docs.google.com/presentation/d/1P5ToVdC_FaFzqC-wD6al6RoLseOgzoyaYESyJasef2E/edit#slide=id.g3949f8d8a6_137_0) for this [course website](http://speech.ee.ntu.edu.tw/~tlkagk/courses_MLDS18.html) for more details.

**Comment by siryne** [comment]
thank you so much.
